routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web Routes for your application. These
| Routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/* 
|--------------------------------------------------------------------------
| User Routes
|--------------------------------------------------------------------------
*/

use App\Http\Controllers\PesertaController;
use App\Http\Controllers\DropzoneController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\adminController;

Route::get('/', [
    'as' => 'landing-page',
    'uses' => 'HomeController@landing_page'
]);

Route::match(['post', 'get'], '/login', [
    'as' => 'login',
    'uses' => 'HomeController@login'
]);

Route::match(['post', 'get'], '/registrasi', [
    'as' => 'registrasi',
    'uses' => 'HomeController@registrasi'
]);

Route::get('/registrasi/verifikasi/{tipe}/{confirmationCode}', [
    'as' => 'confirmation_path',
    'uses' => 'HomeController@confirm'
]);

Route::get('/resend/{type}/{email}', [
    'as'    => 'resend',
    'uses'  => 'HomeController@reSendEmail'
]);

Route::group(['middleware'=>'auth:peserta', 'as'=>'user.'], function () {
    Route::get('/dashboard',  [PesertaController::class, 'dashboard'])->name('dashboard');

    Route::get(
        '/pengumuman', 
        [PesertaController::class, 'view_pengumuman']
    )->name('pengumuman');

    Route::get(
        '/email', 
        [PesertaController::class, 'send_email']
    )->name('email');

    Route::match(['post', 'get'], '/profile', [
        'as' => 'profile',
        'uses' => 'PesertaController@update_profile'
    ]);

    Route::get(
        '/tata-cara-pendaftaran', 
        [PesertaController::class, 'view_tata_cara_pendaftaran']
    )->name('tata-cara-pendaftaran');

    Route::get(
        '/kontak', 
        [PesertaController::class, 'view_kontak']
    )->name('kontak');

    Route::get(
        '/sertifikat', 
        [PesertaController::class, 'view_list_sertifikat']
    )->name('list-sertifikat');

    Route::get(
        '/sertifikat/download/{id}', 
        [PesertaController::class, 'download_sertif']
    )->name('download-sertifikat');

    Route::get(
        '/file-lkti', 
        [DropzoneController::class, 'index']
    )->name('lkti-view');

    Route::post(
        '/file-lkti/upload', 
        [DropzoneController::class, 'store']
    )->name('lkti-upload');

    Route::post(
        '/file-lkti/delete', 
        [DropzoneController::class, 'destroy']
    )->name('lkti-delete');
    
    Route::match(['post', 'get'], '/pilih-kontes', [
        'as' => 'pilih-kontes',
        'uses' => 'PesertaController@pilih_kontes'
    ]);

    Route::match(['post', 'get'], '/pendaftaran-tim', [
        'as' => 'daftarkan-tim',
        'uses' => 'PesertaController@daftarkan_tim'
    ]);


    Route::match(['post', 'get'], '/konfirmasi-pembayaran', [
        'as' => 'konfirmasi-pembayaran',
        'uses' => 'PesertaController@konfirmasi_pembayaran'
    ]);

    Route::get(
        '/status-pendaftaran', 
        [PesertaController::class, 'status_pendaftaran']
        )->name('status-pendaftaran');

        Route::get(
            '/kunci-data', 
            [PesertaController::class, 'kunci_data']
        )->name('kunci-data');

    Route::post(
        '/lihat-kontes', 
        [PesertaController::class, 'lihat_kontes']
        )->name('lihat-kontes');

    Route::match(['post', 'get'], '/cetak_kartu', [
        'as' => 'cetak-kartu',
        'uses' => 'PesertaController@cetak_kartu'
    ]);

    Route::get('/logout', 'PesertaController@logout')->name('logout');
});

/* 
|--------------------------------------------------------------------------
| End User Routes
|--------------------------------------------------------------------------
*/


/* 
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
*/
Route::prefix('admin')->group(function () {
    /* Route REGIS LOGIN*/
    
    Route::match(['post', 'get'], '/login', [
        'as' => 'login-admin',
        'uses' => 'adminController@login'
    ]);
    
    Route::match(['post', 'get'], '/registrasi', [
        'as' => 'registrasi-admin',
        'uses' => 'adminController@registrasi'
    ]);


Route::group(['middleware'=>'auth:admin'], function () {
    Route::get('/beranda',function(){
        return view('Dashboard.beranda_admin'); #nampilin blade beranda
    });
    
    Route::get('/','berandaController@index')->name('beranda-admin');
    /*Contoh ajax route */
    /*Route::get('product-list', [ProductController::class, 'index']);
    Route::get('product-list/{id}/edit', [ProductController::class, 'edit']);
    Route::post('product-list/store', [ProductController::class, 'store']);
    Route::get('product-list/delete/{id}', [ProductController::class, 'destroy']);*/
    
    /*Route Email */
    Route::get(
        '/email', 
        [emailController::class, 'send_email']
    )->name('email');

    /*Route Data Team */
    Route::get('/data-team','teamController@index')->name('data-team');


    /*Route Peserta/User*/
    Route::get('/data-user','userController@index')->name('data-user');
    //edit/update
    Route::get('/edit-user/{id}','userController@edit')->name('edit-user');
        
    Route::post('/update-user/{id}','userController@update')->name('update-user');

    /* Route transaksi */
    //create
    Route::get('/transaksi-baru','purchaseController@index')->name('transaksi-baru');
    Route::get('/transaksi-disetujui','purchaseController@index_disetujui')->name('transaksi-disetujui');
    Route::get('/transaksi-ditolak','purchaseController@index_ditolak')->name('transaksi-ditolak');

    //edit/update
    Route::get('/edit-transaksi/{id}','purchaseController@edit')->name('edit-transaksi');
    
    Route::post('/update-transaksi/{id}','purchaseController@update')->name('update-transaksi');

    //update status pembayaran
    Route::get('/update-statusPembayaran/{id}','purchaseController@update_statusPembayaran')->name('update-statusPembayaran');

    //delete
    Route::get('/delete-transaksi/{id}','purchaseController@destroy')->name('delete-transaksi');


    /* Route KONTES */
    //create
    Route::get('/data-kontes','kontesController@index')->name('data-kontes');
    
    Route::get('/create-kontes','kontesController@create')->name('create-kontes');
    
    Route::post('/simpan-kontes','kontesController@store')->name('simpan-kontes');

    //update
    Route::get('/update-statusKontes/{id}','kontesController@update_statusKontes')->name('update-statusKontes');

    Route::get('/update-jenisKontes/{id}','kontesController@update_jenisKontes')->name('update-jenisKontes');
    
    //edit/update
    Route::get('/edit-kontes/{id}','kontesController@edit')->name('edit-kontes');
    
    Route::post('/update-kontes/{id}','kontesController@update')->name('update-kontes');
    
    //delete
    Route::get('/delete-kontes/{id}','kontesController@destroy')->name('delete-kontes');
    
    /*Route TAHAPAN KONTES*/
    //create
    Route::get('/data-tahapan','tahapanController@index')->name('data-tahapan');
    //ajax tahapan
    Route::get('getdtahapan',[
        'uses'=>'tahapanController@getdtahapan',
        'as'=>'ajax.getdtahapan',
    ]);
    //ajax kontes
    Route::get('getdkontes',[
        'uses'=>'kontesController@getdkontes',
        'as'=>'ajax.getdkontes',
    ]);
    //ajax transaksi
    Route::get('getdtransaksi',[
        'uses'=>'purchaseController@getdtransaksi',
        'as'=>'ajax.getdtransaksi',
    ]);

    Route::get('getdtransaksi_ditolak',[
        'uses'=>'purchaseController@getdtransaksi_ditolak',
        'as'=>'ajax.getdtransaksi_ditolak',
    ]);

    Route::get('getdtransaksi_disetujui',[
        'uses'=>'purchaseController@getdtransaksi_disetujui',
        'as'=>'ajax.getdtransaksi_disetujui',
    ]);
    //ajax peserta
    Route::get('getdpeserta',[
        'uses'=>'userController@getdpeserta',
        'as'=>'ajax.getdpeserta',
    ]);
    //ajax data team
    Route::get('getdteam',[
        'uses'=>'teamController@getdteam',
        'as'=>'ajax.getdteam',
    ]);
    
    //create tahapan
    Route::get('/create-tahapan','tahapanController@create')->name('create-tahapan');
    
    Route::post('/simpan-tahapan','tahapanController@store')->name('simpan-tahapan');
    
    Route::get('/update-statusTahapan/{id}','tahapanController@update_statusTahapan')->name('update-statusTahapan');
    
    //edit/update
    Route::get('/edit-tahapan/{id}','tahapanController@edit')->name('edit-tahapan');
    
    Route::post('/update-tahapan/{id}','tahapanController@update')->name('update-tahapan');
    
    //delete
    Route::get('/delete-tahapan/{id}','tahapanController@destroy')->name('delete-tahapan');

    Route::get('/logout', 'adminController@logout')->name('logout');

});
}); 

/* 
|--------------------------------------------------------------------------
| End Admin Routes
|--------------------------------------------------------------------------
*/

resources/views/User-Layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/User-Layouts/footer.blade.php
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2020</span>
        </div>
    </div>
</footer>

resources/views/User-Layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="csrf-token" content="{{ csrf_token() }}"> 
    <!-- The above meta tags *must* come first in the head -->

    <!-- SEO Meta Tags -->
    <title>Campuspedia | @yield('title')</title>
    <meta name="description" content="Website Campuspedia">
    <meta name="keywords" content="Olimpiade, Event, Conference, Academic, School, Scholar" />
    <meta name="author" content="Campuspedia">

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{{asset('css/sb-admin-2.min.css')}}" rel="stylesheet">
    <link href="{{asset('css/custom.css')}}" rel="stylesheet">
    @yield('extracss')
    @yield('extrajs')
</head>

<body id="page-top">
    @include('sweetalert::alert')

    <!-- Page Wrapper -->
    @if (Route::has('login'))
        @if (Auth::check())
        <div id="wrapper">
            @include('User-Layouts.sidebar')

            <!-- Content Wrapper -->
            <div id="content-wrapper" class="d-flex flex-column">
                <!-- Main Content -->
                <div id="content">
                    @include('User-Layouts.topbar')

                    <!-- Begin Page Content -->
                    <div class="container-fluid">
                        @yield('content')
                    </div>
                    <!-- /.container-fluid -->
                </div>
                <!-- End of Main Content -->

                <!-- Footer -->
                @section('footer')
                    @include('User-Layouts.footer')
                @endsection
                <!-- End of Footer -->

            </div>
            <!-- End of Content Wrapper -->

        </div>
        <!-- End of Page Wrapper -->

        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fas fa-angle-up"></i>
        </a>

        <!-- Logout Modal-->
        <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <a class="btn btn-primary" href="{{ route('user.logout') }}">Logout</a>
                    </div>
                </div>
            </div>
        </div>
        @endif
    @endif

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>
    
    @include('sweetalert::alert')
    <script>
        $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
        });
    </script>

</body>

</html>

resources/views/User-Layouts/sidebar.blade.php
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
   
    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/dashboard">
        <div class="sidebar-brand-icon">
            <img src="images/logo.png" style="width:90%" alt="">
        </div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <div class="nav-item profile-user flex-column justify-content-center py-2">
       
        @if ($peserta->url_photo_profile == null)
            <img class="img-profile rounded-circle" style="width:80%;height:auto;margin:auto;" src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="">
        @else
            <img class="img-profile rounded-circle" style="width:80%;height:auto;margin:auto;" src="{{ Storage::url($peserta->url_photo_profile) }}"  alt="">                                                 
        @endif
        
        <div class="nav-link flex align-items-center text-center text-white">
            <span style="font-size: 1em;"><strong>{{ $peserta->nama_lengkap }}</strong></span>
            <div class="user-info mt-2">
                <a class="label label-info" href="{{route('user.profile')}}" style="border-radius:25px;cursor:pointer;color:white;text-decoration:none;">
                    <i class="fas fa-fw fa-user"></i> 
                    <span>Lihat Profil</span> 
                </a>
            </div>
        </div>
    </div>

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{{route('user.dashboard')}}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>

    <!-- Nav Item - Informasi Olimpiade -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
            aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-cog"></i>
            <span>Informasi Olimpiade</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="{{route('user.status-pendaftaran')}}">Status Pendaftaran</a>
                <a class="collapse-item" href="{{route('user.pengumuman')}}">Pengumuman</a>
                <a class="collapse-item" href="{{route('user.list-sertifikat')}}">Sertifikat Anda</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Tata Cara Pendaftaran -->
     <li class="nav-item">
        <a class="nav-link" href="{{route('user.tata-cara-pendaftaran')}}">
            <i class="fas fa-fw fa-table"></i>
            <span>Tata Cara Pendaftaran</span></a>
    </li>


    <!-- Nav Item - Daftar Olimpiade -->
    <li class="nav-item">
        <a class="nav-link" href="{{route('user.pilih-kontes')}}">
            <i class="fas fa-fw fa-table"></i>
            <span>Daftar Olimpiade</span></a>
    </li>

    <!-- Nav Item - Kontak -->
    <li class="nav-item">
        <a class="nav-link" href="{{route('user.kontak')}}">
            <i class="fas fa-fw fa-table"></i>
            <span>Kontak</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
</ul>
<!-- End of Sidebar -->

resources/views/User-Layouts/topbar.blade.php
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Search -->
    <form
        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Cari Olimpiade..."
                aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small"
                            placeholder="Search for..." aria-label="Search"
                            aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Nav Item - Alerts -->
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">3+</span>
            </a>
            <!-- Dropdown - Alerts -->
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                    Alerts Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                        <div class="icon-circle bg-primary">
                            <i class="fas fa-file-alt text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">December 12, 2019</div>
                        <span class="font-weight-bold">A new monthly report is ready to download!</span>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                        <div class="icon-circle bg-success">
                            <i class="fas fa-donate text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">December 7, 2019</div>
                        $290.29 has been deposited into your account!
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                        <div class="icon-circle bg-warning">
                            <i class="fas fa-exclamation-triangle text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">December 2, 2019</div>
                        Spending Alert: We've noticed unusually high spending for your account.
                    </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
            </div>
        </li>

        <!-- Nav Item - Messages -->
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-envelope fa-fw"></i>
                <!-- Counter - Messages -->
                <span class="badge badge-danger badge-counter">7</span>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="messagesDropdown">
                <h6 class="dropdown-header">
                    Message Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="img/undraw_profile_1.svg"
                            alt="">
                        <div class="status-indicator bg-success"></div>
                    </div>
                    <div class="font-weight-bold">
                        <div class="text-truncate">Hi there! I am wondering if you can help me with a
                            problem I've been having.</div>
                        <div class="small text-gray-500">Emily Fowler · 58m</div>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="img/undraw_profile_2.svg"
                            alt="">
                        <div class="status-indicator"></div>
                    </div>
                    <div>
                        <div class="text-truncate">I have the photos that you ordered last month, how
                            would you like them sent to you?</div>
                        <div class="small text-gray-500">Jae Chun · 1d</div>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="img/undraw_profile_3.svg"
                            alt="">
                        <div class="status-indicator bg-warning"></div>
                    </div>
                    <div>
                        <div class="text-truncate">Last month's report looks great, I am very happy with
                            the progress so far, keep up the good work!</div>
                        <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60"
                            alt="">
                        <div class="status-indicator bg-success"></div>
                    </div>
                    <div>
                        <div class="text-truncate">Am I a good boy? The reason I ask is because someone
                            told me that people say this to all dogs, even if they aren't good...</div>
                        <div class="small text-gray-500">Chicken the Dog · 2w</div>
                    </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
            </div>
        </li>

        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small"> {{ Auth::user()->name }} </span>
                @if ($peserta->url_photo_profile == null)
                <img class="img-profile rounded-circle" src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="">
              @else
                <img class="img-profile rounded-circle" src="{{ Storage::url($peserta->url_photo_profile) }}"  alt="">                                                 
              @endif
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{{route('user.profile')}}">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profile
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    Settings
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                    Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
            </div>
        </li>

    </ul>

</nav>
<!-- End of Topbar -->